# Generated by Django 6.0.8 on 2026-09-04 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_id', models.CharField(max_length=20, unique=True, verbose_name='分享码')),
                ('channel', models.CharField(blank=True, max_length=30, verbose_name='分享渠道')),
                ('click_count', models.IntegerField(default=0, verbose_name='点击数')),
                ('register_count', models.IntegerField(default=0, verbose_name='注册数')),
                ('download_count', models.IntegerField(default=0, verbose_name='下载数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='分享时间')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resource', verbose_name='分享的资源')),
                ('sharer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='分享者')),
            ],
            options={
                'verbose_name': '分享追踪',
                'verbose_name_plural': '分享追踪',
                'db_table': 'shares_share',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['share_id'], name='shares_shar_share_i_de65cd_idx'), models.Index(fields=['sharer', '-created_at'], name='shares_shar_sharer__665138_idx')],
            },
        ),
    ]
