# Generated by Django 6.1.1 on 2026-09-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_free_downloads',
            field=models.IntegerField(default=0, verbose_name='今日已用免费下载次数'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_free_date',
            field=models.DateField(blank=True, null=True, verbose_name='上次免费下载日期'),
        ),
    ]
