# Generated by Django 6.1.1 on 2026-09-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_daily_free_downloads_user_last_free_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invite_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
