# Generated by Django 6.1.1 on 2026-09-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_invite_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='invite_code',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='上传自定义头像，为空则显示默认青蛙头像', null=True, upload_to='avatars/%Y/%m/', verbose_name='头像'),
        ),
    ]
