# Generated by Django 6.0.8 on 2026-09-04 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OilTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='变动数量')),
                ('balance_after', models.IntegerField(verbose_name='交易后余额')),
                ('type', models.CharField(choices=[('register_bonus', '注册奖励'), ('daily_login', '每日登录'), ('share_click', '分享点击'), ('share_register', '分享注册'), ('share_download', '分享下载'), ('upload_earning', '上传收益'), ('download_payment', '下载支付'), ('upvote_reward', '点赞奖励'), ('collect_reward', '收藏奖励'), ('comment_up_reward', '评论被顶'), ('admin_adjust', '管理员调整')], max_length=30, verbose_name='交易类型')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='交易时间')),
                ('related_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.resource', verbose_name='关联资源')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_transactions', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '油滴交易',
                'verbose_name_plural': '油滴交易',
                'db_table': 'transactions_oiltransaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='transaction_user_id_f32b17_idx'), models.Index(fields=['type'], name='transaction_type_52d091_idx')],
            },
        ),
    ]
