# Generated by Django 6.1.1 on 2026-09-06 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource_extract_code_alter_resource_download_url'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oiltransaction',
            name='related_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.comment', verbose_name='关联评论'),
        ),
    ]
