# Generated by Django 6.1.1 on 2026-09-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_oiltransaction_related_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oiltransaction',
            name='type',
            field=models.CharField(choices=[('register_bonus', '注册奖励'), ('daily_login', '每日登录'), ('share_click', '分享点击'), ('share_register', '分享注册'), ('share_download', '分享下载'), ('upload_earning', '上传收益'), ('download_payment', '下载支付'), ('upvote_reward', '点赞奖励'), ('collect_reward', '收藏奖励'), ('comment_up_reward', '评论被顶'), ('admin_adjust', '管理员调整'), ('invite_reward', '邀请奖励')], max_length=30, verbose_name='交易类型'),
        ),
    ]
