# Generated by Django 6.0.8 on 2026-09-04 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('grade', models.CharField(blank=True, choices=[('小学', '小学'), ('初中', '初中'), ('高中', '高中')], max_length=20, verbose_name='适用年级')),
                ('resource_type', models.CharField(blank=True, choices=[('视频', '视频'), ('文档', '文档'), ('网站', '网站'), ('APP', 'APP'), ('教具', '教具'), ('其他', '其他')], max_length=20, verbose_name='资源类型')),
                ('cover_images', models.JSONField(blank=True, default=list, verbose_name='预览图列表')),
                ('download_url', models.URLField(max_length=500, verbose_name='下载链接')),
                ('price', models.IntegerField(default=0, verbose_name='油滴价格')),
                ('status', models.CharField(choices=[('published', '已发布'), ('pending', '待审核'), ('rejected', '不通过'), ('expired', '已失效')], default='published', max_length=20, verbose_name='状态')),
                ('ai_risk_score', models.IntegerField(default=0, verbose_name='AI风险评分')),
                ('ai_risk_reason', models.TextField(blank=True, verbose_name='AI风险原因')),
                ('audited_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reject_reason', models.TextField(blank=True, verbose_name='不通过原因')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('download_count', models.IntegerField(default=0, verbose_name='下载次数')),
                ('collect_count', models.IntegerField(default=0, verbose_name='收藏次数')),
                ('upvote_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('downvote_count', models.IntegerField(default=0, verbose_name='踩数')),
                ('avg_rating', models.FloatField(default=0.0, verbose_name='平均评分')),
                ('ai_tags_generated', models.BooleanField(default=False, verbose_name='AI标签已生成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('audited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_resources', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '资源',
                'verbose_name_plural': '资源',
                'db_table': 'resources_resource',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, verbose_name='首次下载时间')),
                ('last_downloaded_at', models.DateTimeField(auto_now=True, verbose_name='最近下载时间')),
                ('is_free_trial', models.BooleanField(default=False, verbose_name='是否免费试用')),
                ('oil_paid', models.IntegerField(default=0, verbose_name='支付油滴数')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resource', verbose_name='资源')),
            ],
            options={
                'verbose_name': '下载记录',
                'verbose_name_plural': '下载记录',
                'db_table': 'resources_download',
                'ordering': ['-last_downloaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('upvote_count', models.IntegerField(default=0, verbose_name='顶数')),
                ('downvote_count', models.IntegerField(default=0, verbose_name='踩数')),
                ('audit_status', models.CharField(choices=[('visible', '已显示'), ('hidden', '待审核'), ('rejected', '不通过')], default='visible', max_length=20, verbose_name='审核状态')),
                ('ai_risk_score', models.IntegerField(default=0, verbose_name='AI风险评分')),
                ('audited_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('audited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_comments', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.comment', verbose_name='父评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resource', verbose_name='资源')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'resources_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resource', verbose_name='资源')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'db_table': 'resources_collect',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('up', '顶'), ('down', '踩')], max_length=10, verbose_name='投票类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投票时间')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.comment', verbose_name='评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '评论投票',
                'verbose_name_plural': '评论投票',
                'db_table': 'resources_commentvote',
                'unique_together': {('user', 'comment')},
            },
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['status', '-created_at'], name='resources_r_status_223b36_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['uploader', '-created_at'], name='resources_r_uploade_a546dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='download',
            unique_together={('user', 'resource')},
        ),
        migrations.AlterUniqueTogether(
            name='collect',
            unique_together={('user', 'resource')},
        ),
    ]
