# Generated by Django 6.1.1 on 2026-09-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='extract_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='提取码'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='download_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='下载链接'),
        ),
    ]
