# Generated by Django 6.1.1 on 2026-09-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource_extract_code_alter_resource_download_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='has_rewarded',
            field=models.BooleanField(default=False, verbose_name='是否已给发布者奖励'),
        ),
    ]
