# Generated by Django 6.1.1 on 2026-09-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_collect_has_rewarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否收藏中'),
        ),
    ]
