# Generated by Django 6.1.1 on 2026-09-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_collect_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalFreeQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True, verbose_name='当前是否可用')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='上次使用时间')),
            ],
            options={
                'verbose_name': '全局免费额度',
                'verbose_name_plural': '全局免费额度',
                'db_table': 'core_global_free_quota',
            },
        ),
    ]
