# Generated by Django 6.1.1 on 2026-09-15 14:27

import django.db.models.deletion
import resources.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_globalfreequota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StickerPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分组名称')),
                ('icon', models.CharField(default='🐸', help_text='显示在选择器标签上的字符，如 😀 / 🐸', max_length=10, verbose_name='分组图标')),
                ('sort_order', models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '表情包分组',
                'verbose_name_plural': '表情包分组',
                'db_table': 'resources_stickerpack',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='表情名称')),
                ('image', models.ImageField(upload_to=resources.models.sticker_image_path, verbose_name='表情图片')),
                ('sort_order', models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='resources.stickerpack', verbose_name='分组')),
            ],
            options={
                'verbose_name': '自定义表情包',
                'verbose_name_plural': '自定义表情包',
                'db_table': 'resources_sticker',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
