# Generated by Django 6.1.1 on 2026-09-12 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
        ('resources', '0002_resource_extract_code_alter_resource_download_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', '浏览'), ('click', '点击'), ('search', '搜索'), ('collect', '收藏'), ('upvote', '资源点赞'), ('downvote', '资源点踩'), ('download', '下载'), ('free_download', '免费下载'), ('open_link', '打开链接'), ('copy_link', '复制链接'), ('copy_code', '复制提取码'), ('share', '分享'), ('comment', '评论'), ('comment_up', '评论点赞'), ('comment_down', '评论点踩'), ('register', '注册'), ('login', '登录'), ('logout', '退出登录'), ('page_profile', '浏览个人主页'), ('page_my_resources', '浏览我的资源'), ('page_my_collections', '浏览我的收藏'), ('page_my_downloads', '浏览我的下载'), ('page_my_follows', '浏览我的关注'), ('page_my_history', '浏览浏览历史'), ('page_my_shares', '浏览分享历史'), ('page_my_earnings', '浏览收益统计'), ('page_profile_edit', '浏览账号设置'), ('page_ranking', '浏览排行榜'), ('page_notifications', '浏览消息中心'), ('view_notification', '查看消息通知'), ('delete_notification', '删除消息')], max_length=30, verbose_name='行为类型')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='如：{"position": 3, "stay_duration": 12, "search_query": "数学"}', verbose_name='额外数据')),
                ('session_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='会话ID')),
                ('device_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='设备ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='行为时间')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.resource', verbose_name='资源')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户行为',
                'verbose_name_plural': '用户行为',
                'db_table': 'recommendations_behavior',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='recommendat_user_id_0345e1_idx'), models.Index(fields=['resource', 'action'], name='recommendat_resourc_fe03f8_idx'), models.Index(fields=['action', '-created_at'], name='recommendat_action_5c44c0_idx'), models.Index(fields=['-created_at'], name='recommendat_created_ccc7ae_idx')],
            },
        ),
    ]
